@startuml
'https://plantuml.com/activity-diagram-beta

start
:免费领取接口被调用;
:从数据库中获取数据;
note right
game_id
user_id
end note
:获取用户真实注册时间;
if (用户是当天注册的,\n且用户未领取免费装扮) then (yes)
    :发送装扮到背包;
else (no)
endif
:返回调用成功;
stop

@enduml
