@startuml
'https://plantuml.com/activity-diagram-beta

start
:获取前端传递信息;
note right
type Param struct {
    UserId int
    Robots bool
}
end note
if (Robots = false) then (false)
    :查找数据库中\n玩家当前使用的装扮;
    note left
    game_id
    user_id
    in_use 是否正在使用
    has_expired 是否已过期
    end note
    :再次判断\n正在使用的装扮\n是否已过期;
    note left
    has_time_limit 是否有时间控制
    expire_at 失效于
    end note
    if (是否过期) then (过期)
        :修改\nin_use为未使用;
        :提示已过期;
    else (未过期)
    endif
else (true)
    :10%操作下面的操作;
    :随机从数据库中获取一系列装扮;
endif
:拼接为前端需求接口数据;
:返回数据;
stop

@enduml
